# Generated by Django 3.2 on 2023-01-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoviews',
            name='video_volume',
        ),
    ]
